root: true

env:
  browser: true

parser: "@typescript-eslint/parser"
parserOptions: 
  ecmaVersion: 2021
  sourceType: module

plugins:
  - "@typescript-eslint"
  - "eslint-plugin-react-hooks"
  - "eslint-plugin-jsx-a11y"

extends: 
  - "plugin:@typescript-eslint/recommended"
  - "plugin:eslint-plugin-react-hooks/recommended"
  - "plugin:eslint-plugin-jsx-a11y/recommended"

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn