# Generated by Django 3.0.4 on 2020-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlayout',
            name='description',
            field=models.CharField(default='no desc', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardlayout',
            name='name',
            field=models.CharField(default='no name', max_length=200),
            preserve_default=False,
        ),
    ]
