# Generated by Django 3.0.4 on 2020-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200329_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlayout',
            name='filename',
            field=models.FilePathField(default='app/templates/app/card-base-template.html'),
        ),
    ]
