# Generated by Django 3.0.4 on 2020-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200329_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlayout',
            name='filename',
            field=models.FilePathField(path='/home/s/projects/ebisu-flashcards/django_impl/app/templates/app/card-base-template.html'),
        ),
    ]
