# Generated by Django 3.0.4 on 2020-03-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200329_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlayout',
            name='filename',
            field=models.FilePathField(path='/home/s/projects/ebisu-flashcards/django_impl/app/templates/app/card_templates'),
        ),
    ]
