# Generated by Django 3.0.4 on 2020-03-31 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200331_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebisucardmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='ebisucardmodel',
            name='abstractcardmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractCardModel'),
            preserve_default=False,
        ),
    ]
