# Generated by Django 3.0.4 on 2020-04-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200331_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractcard',
            old_name='deck_id',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='abstractcardmodel',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='abstractcardmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
