# Generated by Django 3.0.4 on 2020-04-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200401_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomOrderCard',
            fields=[
                ('abstractcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractCard')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.abstractcard',),
        ),
        migrations.CreateModel(
            name='RandomOrderCardModel',
            fields=[
                ('abstractcardmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractCardModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.abstractcardmodel',),
        ),
        migrations.CreateModel(
            name='RandomOrderDeck',
            fields=[
                ('abstractdeck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractDeck')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.abstractdeck',),
        ),
        migrations.AlterField(
            model_name='abstractcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app.AbstractDeck'),
        ),
    ]
