# Generated by Django 3.0.4 on 2020-04-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0012_auto_20200404_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractcard',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.abstractcard_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='abstractcardmodel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.abstractcardmodel_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='abstractdeck',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.abstractdeck_set+', to='contenttypes.ContentType'),
        ),
    ]
