# Generated by Django 3.0.4 on 2020-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200404_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlayout',
            name='filename',
            field=models.FilePathField(max_length=500, path='/home/s/projects/ebisu-flashcards/django_impl/app/templates/app/card_templates'),
        ),
    ]
