# Generated by Django 3.0.4 on 2020-04-06 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0015_auto_20200405_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractcard',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='abstractdeck',
            name='default_layout',
        ),
        migrations.RemoveField(
            model_name='abstractcard',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='abstractcard',
            name='question',
        ),
        migrations.AlterField(
            model_name='abstractcardmodel',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.AbstractCard'),
        ),
        migrations.AlterField(
            model_name='abstractcardmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AbstractCardFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.abstractcardfact_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='abstractcard',
            name='answer',
            field=models.ManyToManyField(related_name='answer', to='app.AbstractCardFact'),
        ),
        migrations.AddField(
            model_name='abstractcard',
            name='question',
            field=models.ManyToManyField(related_name='question', to='app.AbstractCardFact'),
        ),
    ]
