# Generated by Django 3.0.4 on 2020-04-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200406_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractcard',
            name='answer',
        ),
        migrations.AddField(
            model_name='abstractcard',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.AbstractCardFact'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='abstractcard',
            name='question',
        ),
        migrations.AddField(
            model_name='abstractcard',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app.AbstractCardFact'),
            preserve_default=False,
        ),
    ]
