# Generated by Django 3.0.4 on 2020-04-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200406_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('filename', models.FilePathField(max_length=500, path='/home/s/projects/ebisu-flashcards/django_impl/app/templates/app/fact_templates')),
            ],
        ),
        migrations.CreateModel(
            name='HtmlCardFact',
            fields=[
                ('abstractcardfact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractCardFact')),
                ('content', models.CharField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.abstractcardfact',),
        ),
        migrations.CreateModel(
            name='ImageCardFact',
            fields=[
                ('abstractcardfact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractCardFact')),
                ('content', models.FilePathField(max_length=500, path='/home/s/projects/ebisu-flashcards/django_impl/app/uploads/app/image_facts')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.abstractcardfact',),
        ),
        migrations.CreateModel(
            name='TextCardFact',
            fields=[
                ('abstractcardfact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractCardFact')),
                ('content', models.CharField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.abstractcardfact',),
        ),
        migrations.DeleteModel(
            name='CardLayout',
        ),
        migrations.AlterField(
            model_name='abstractcard',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='as_answer', to='app.AbstractCardFact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractcard',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='as_question', to='app.AbstractCardFact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractcardfact',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='app.FactLayout'),
            preserve_default=False,
        ),
    ]
